C		PROGRAM TO GENERATE NUMBERS IN FIBO SERIES

		INTEGER N, OUTPUT
		READ *, N
		IA= 0
		IB= 1
		WRITE(*,*) IA,IB
		DO 100 I=1,N-1
		IA=IB
		IB=OUTPUT
		OUTPUT= IA+IB
		WRITE(*,*)	OUTPUT
100		CONTINUE
		END